# Generated by Django 3.2.8 on 2021-10-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
